<a href="https://colab.research.google.com/github/SiddheshKamthe/Abc/blob/main/SklearnPrg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Scikit-Learn Functions

# 1) Load dataset
from sklearn.datasets import load_iris
print("1. Loading the Iris dataset...")
iris = load_iris()

# 2) Feature names
print("2. Feature names:", iris.feature_names)

# 3) Target names
print("3. Target names:", iris.target_names)

# 4) Print data
print("4. Data:\n", iris.data)

# 5) Split the dataset
from sklearn.model_selection import train_test_split
print("5. Splitting the dataset into training and testing sets...")
x = iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

# 6) Get shape
print("6. Shape of the training set:", x_train.shape)

# 7) Train the model
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
print("7. Training the K-Neighbors Classifier model...")
classifier_knn = KNeighborsClassifier(n_neighbors=3)
classifier_knn.fit(x_train, y_train)
y_pred = classifier_knn.predict(x_test)

# 8) Get accuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print("8. Accuracy =", accuracy)

# 9) Precision score with macro
prec_macro = metrics.precision_score(y_test, y_pred, average="macro")
print("9. Precision (macro) =", prec_macro)

# 10) Precision score with micro
prec_micro = metrics.precision_score(y_test, y_pred, average="micro")
print("10. Precision (micro) =", prec_micro)

# 11) F1 score
f1 = metrics.f1_score(y_test, y_pred, average="macro")
print("11. F1 Score =", f1)

# 12) Mean squared error
mse = metrics.mean_squared_error(y_test, y_pred)
print("12. Mean Squared Error =", mse)

# 13) Confusion matrix
cm = metrics.confusion_matrix(y_test, y_pred)
print("13. Confusion Matrix:\n", cm)

# 14) Classification report
report = metrics.classification_report(y_test, y_pred)
print("14. Classification Report:\n", report)

# 15) Binarization
import numpy as np
from sklearn import preprocessing
input_data = np.array([[1, -3, 4], [-2, 4, 0], [3, 6, 9]])
print("15. Binarizing input data with threshold 0.5...")
data_binarised = preprocessing.Binarizer(threshold=0.5).transform(input_data)
print("Binarized Data:\n", data_binarised)

# 16) Mean removal
print("16. Scaling the input data (mean removal)...")
data_scaled = preprocessing.scale(input_data)
print("Scaled Mean:", data_scaled.mean(axis=0))
print("Scaled Std:", data_scaled.std(axis=0))

# 17) L1 normalization
print("17. Performing L1 normalization on input data...")
l1 = preprocessing.normalize(input_data, norm="l1")
print("L1 Normalized Data:\n", l1)

# 18) L2 normalization
print("18. Performing L2 normalization on input data...")
l2 = preprocessing.normalize(input_data, norm="l2")
print("L2 Normalized Data:\n", l2)

# 19) Label encoder
print("19. Encoding labels using LabelEncoder...")
le = preprocessing.LabelEncoder()
l_encoded = le.fit_transform(["Pune", "Mumbai", "Pune", "Nashik"])
print("Encoded Labels:", l_encoded)

# 20) Import model
from sklearn.linear_model import LogisticRegression
print("20. Importing Logistic Regression model...")

# 21) Fit logistic regression
print("21. Fitting Logistic Regression model...")
model_logistic = LogisticRegression().fit(x_train, y_train)

# 22) Fit random forest classifier
from sklearn.ensemble import RandomForestClassifier
print("22. Fitting Random Forest Classifier model...")
model_rf = RandomForestClassifier().fit(x_train, y_train)

# 23) Scale features using StandardScaler
from sklearn.preprocessing import StandardScaler
print("23. Scaling features using StandardScaler...")
scaler_std = StandardScaler().fit(x_train)
x_train_scaled_std = scaler_std.transform(x_train)

# 24) Scale features using MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
print("24. Scaling features using MinMaxScaler...")
scaler_minmax = MinMaxScaler().fit(x_train)
x_train_scaled_minmax = scaler_minmax.transform(x_train)

# 25) Recall score
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, average="macro")
print("25. Recall Score (macro):", recall)

# 26) Import PCA
from sklearn.decomposition import PCA
print("26. Importing PCA for dimensionality reduction...")

# 27) Perform PCA for dimension reduction
pca = PCA(n_components=2)
print("27. Performing PCA to reduce dimensions to 2...")
x_pca = pca.fit_transform(x)
print("PCA Transformed Data:\n", x_pca)


1. Loading the Iris dataset...
2. Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
3. Target names: ['setosa' 'versicolor' 'virginica']
4. Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3