<a href="https://colab.research.google.com/github/SiddheshKamthe/Abc/blob/main/TensorFlowPrg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

# 1) Constant
hello = tf.constant("Hello, tensorflow!")
print(hello.numpy())  # Convert to numpy for printing

# 2) 1D array
array_1d = tf.constant([1, 2, 3, 4, 5])
print(array_1d)

# 3) 2D array
array_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print(array_2d)

# 4) 3D array
array_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d)

# 5) 4D array
array_4d = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(array_4d)

# 6) 5D array
array_5d = tf.constant([[[[[1, 2], [3, 4]]]]])
print(array_5d)

# 7) Element-wise addition
a1 = tf.constant([1, 2, 3, 4])
a2 = tf.constant([4, 3, 2, 1])
result_add = tf.add(a1, a2)
print(result_add)

# 8) Element-wise multiplication
result_mul = tf.multiply(a1, a2)
print(result_mul)

# 9) Matrix multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result_mat_mul = tf.matmul(matrix_a, matrix_b)
print(result_mat_mul)

# 10) Transpose
transposed = tf.transpose(array_2d)
print(transposed)

# 11) Reshaping
reshaped = tf.reshape(array_1d, (1, 5))
print(reshaped)

# 12) Subtract
result_sub = tf.subtract(5, 2)
print(result_sub)

# 13) Divide
result_div = tf.divide(6, 2)
print(result_div)

# 14) Reduce sum
reduce_sum = tf.reduce_sum([1, 2, 3])
print(reduce_sum)

# 15) Reduce mean
reduce_mean = tf.reduce_mean([1, 2, 3])
print(reduce_mean)

# 16) Reduce max
reduce_max = tf.reduce_max([1, 2, 3])
print(reduce_max)

# 17) Reduce min
reduce_min = tf.reduce_min([1, 2, 3])
print(reduce_min)

# 18) Square
result_square = tf.square(3)
print(result_square)

# 19) Square root
result_sqrt = tf.sqrt(9.0)  # TensorFlow requires float for sqrt
print(result_sqrt)

# 20) Exponential
result_exp = tf.exp(2.0)
print(result_exp)

# 21) Logarithm
result_log = tf.math.log(10.0)
print(result_log)

# 22) Sine
result_sin = tf.sin(3.14)
print(result_sin)

# 23) Cosine
result_cos = tf.cos(3.14)
print(result_cos)

# 24) Tangent
result_tan = tf.tan(3.14)
print(result_tan)

# 25) Absolute value
result_abs = tf.abs(-5)
print(result_abs)

# 26) Floor
result_floor = tf.floor(3.7)
print(result_floor)

# 27) Ceil
result_ceil = tf.math.ceil(3.7)
print(result_ceil)

# 28) Concatenate
arr1 = tf.constant([1, 2])
arr2 = tf.constant([3, 4])
result_concat = tf.concat([arr1, arr2], axis=0)
print(result_concat)

# 29) Ones
ones_array = tf.ones([2, 2])
print(ones_array)

# 30) Zeros
zeros_array = tf.zeros([2, 2])
print(zeros_array)

# 31) Reduce product
reduce_prod = tf.reduce_prod([1, 2, 3])
print(reduce_prod)

# 32) Equal
result_equal = tf.equal(5, 5)
print(result_equal)

# 33) Greater
result_greater = tf.greater(2, 3)
print(result_greater)

# 34) Less
result_less = tf.less(2, 3)
print(result_less)

# 35) Less equal
result_less_equal = tf.less_equal(2, 3)
print(result_less_equal)

# 36) Not equal
result_not_equal = tf.not_equal(5, 4)
print(result_not_equal)

# 37) Greater equal
result_greater_equal = tf.greater_equal(5, 5)
print(result_greater_equal)

# 38) Reduce any
reduce_any = tf.reduce_any([True, False, True])
print(reduce_any)

# 39) Reduce all
reduce_all = tf.reduce_all([True, True, True])
print(reduce_all)

# 40) Cast
result_cast = tf.cast(5.5, tf.int32)
print(result_cast)

# 41) Fill
result_fill = tf.fill([2, 2], 9)
print(result_fill)


b'Hello, tensorflow!'
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]], shape=(1, 2, 2, 2), dtype=int32)
tf.Tensor(
[[[[[1 2]
    [3 4]]]]], shape=(1, 1, 1, 2, 2), dtype=int32)
tf.Tensor([5 5 5 5], shape=(4,), dtype=int32)
tf.Tensor([4 6 6 4], shape=(4,), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(7.389056, shape=(), dtype=float32)
tf.Tensor(2.3025851, shape=(), d