<a href="https://colab.research.google.com/github/SiddheshKamthe/Abc/blob/main/TensorFlowPrg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

# 1) Constant
hello = tf.constant("Hello, TensorFlow!")
print("1) Constant:", hello.numpy().decode())

# 2) 1D array
array_1d = tf.constant([1, 2, 3, 4, 5])
print("2) 1D array:", array_1d.numpy())

# 3) 2D array
array_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print("3) 2D array:", array_2d.numpy())

# 4) 3D array
array_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("4) 3D array:", array_3d.numpy())

# 5) 4D array
array_4d = tf.constant([[[[1]]]])
print("5) 4D array:", array_4d.numpy())

# 6) 5D array
array_5d = tf.constant([[[[[1]]]]])
print("6) 5D array:", array_5d.numpy())

# 7) Element-wise addition
a1 = tf.constant([1, 2, 3, 4])
a2 = tf.constant([4, 3, 2, 1])
result_add = tf.add(a1, a2)
print("7) Element-wise addition:", result_add.numpy())

# 8) Element-wise multiplication
result_multiply = tf.multiply(a1, a2)
print("8) Element-wise multiplication:", result_multiply.numpy())

# 9) Matrix multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result_mat_mul = tf.matmul(matrix_a, matrix_b)
print("9) Matrix multiplication:\n", result_mat_mul.numpy())

# 10) Transpose
transposed = tf.transpose(array_2d)
print("10) Transposed 2D array:\n", transposed.numpy())

# 11) Reshaping
reshaped = tf.reshape(array_1d, (1, 5))
print("11) Reshaped 1D array:\n", reshaped.numpy())

# 12) Subtract
result_subtract = tf.subtract(5, 2)
print("12) Subtract (5 - 2):", result_subtract.numpy())

# 13) Divide
result_divide = tf.divide(6, 2)
print("13) Divide (6 / 2):", result_divide.numpy())

# 14) Reduce sum
reduce_sum = tf.reduce_sum([1, 2, 3])
print("14) Reduce sum of [1, 2, 3]:", reduce_sum.numpy())

# 15) Reduce mean
reduce_mean = tf.reduce_mean([1, 2, 3])
print("15) Reduce mean of [1, 2, 3]:", reduce_mean.numpy())

# 16) Reduce max
reduce_max = tf.reduce_max([1, 2, 3])
print("16) Reduce max of [1, 2, 3]:", reduce_max.numpy())

# 17) Reduce min
reduce_min = tf.reduce_min([1, 2, 3])
print("17) Reduce min of [1, 2, 3]:", reduce_min.numpy())

# 18) Square
result_square = tf.square(3)
print("18) Square of 3:", result_square.numpy())

# 19) Sqrt
result_sqrt = tf.sqrt(9.0)
print("19) Square root of 9:", result_sqrt.numpy())

# 20) Exponential
result_exp = tf.exp(2.0)
print("20) Exponential of 2.0:", result_exp.numpy())

# 21) Logarithm
result_log = tf.math.log(10.0)
print("21) Logarithm of 10.0:", result_log.numpy())

# 22) Sine
result_sin = tf.sin(3.14)
print("22) Sine of 3.14:", result_sin.numpy())

# 23) Cosine
result_cos = tf.cos(3.14)
print("23) Cosine of 3.14:", result_cos.numpy())

# 24) Tangent
result_tan = tf.tan(3.14)
print("24) Tangent of 3.14:", result_tan.numpy())

# 25) Absolute
result_abs = tf.abs(-5)
print("25) Absolute of -5:", result_abs.numpy())

# 26) Floor
result_floor = tf.floor(3.7)
print("26) Floor of 3.7:", result_floor.numpy())

# 27) Ceil
result_ceil = tf.math.ceil(3.7)
print("27) Ceiling of 3.7:", result_ceil.numpy())

# 28) Concatenate
arr1 = tf.constant([[1], [2]])
arr2 = tf.constant([[3], [4]])
result_concat = tf.concat([arr1, arr2], axis=0)
print("28) Concatenated array:\n", result_concat.numpy())

# 29) Ones
result_ones = tf.ones([2, 2])
print("29) Array of ones:\n", result_ones.numpy())

# 30) Zeros
result_zeros = tf.zeros([2, 2])
print("30) Array of zeros:\n", result_zeros.numpy())

# 31) Reduce product
reduce_prod = tf.reduce_prod([1, 2, 3])
print("31) Reduce product of [1, 2, 3]:", reduce_prod.numpy())

# 32) Equal
result_equal = tf.equal(5, 5)
print("32) Is 5 equal to 5?", result_equal.numpy())

# 33) Greater
result_greater = tf.greater(2, 3)
print("33) Is 2 greater than 3?", result_greater.numpy())

# 34) Less
result_less = tf.less(2, 3)
print("34) Is 2 less than 3?", result_less.numpy())

# 35) Less equal
result_less_equal = tf.less_equal(2, 3)
print("35) Is 2 less than or equal to 3?", result_less_equal.numpy())

# 36) Not equal
result_not_equal = tf.not_equal(2, 3)
print("36) Is 2 not equal to 3?", result_not_equal.numpy())

# 37) Greater equal
result_greater_equal = tf.greater_equal(2, 3)
print("37) Is 2 greater than or equal to 3?", result_greater_equal.numpy())

# 38) Reduce any
result_reduce_any = tf.reduce_any([True, False, True])
print("38) Reduce any of [True, False, True]:", result_reduce_any.numpy())

# 39) Reduce all
result_reduce_all = tf.reduce_all([True, True, True])
print("39) Reduce all of [True, True, True]:", result_reduce_all.numpy())

# 40) Cast
result_cast = tf.cast(5.5, tf.int32)
print("40) Cast 5.5 to int32:", result_cast.numpy())

# 41) Fill
result_fill = tf.fill([2, 2], 9)
print("41) Fill array with 9:\n", result_fill.numpy())


1) Constant: Hello, TensorFlow!
2) 1D array: [1 2 3 4 5]
3) 2D array: [[1 2]
 [3 4]
 [5 6]]
4) 3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
5) 4D array: [[[[1]]]]
6) 5D array: [[[[[1]]]]]
7) Element-wise addition: [5 5 5 5]
8) Element-wise multiplication: [4 6 6 4]
9) Matrix multiplication:
 [[19 22]
 [43 50]]
10) Transposed 2D array:
 [[1 3 5]
 [2 4 6]]
11) Reshaped 1D array:
 [[1 2 3 4 5]]
12) Subtract (5 - 2): 3
13) Divide (6 / 2): 3.0
14) Reduce sum of [1, 2, 3]: 6
15) Reduce mean of [1, 2, 3]: 2
16) Reduce max of [1, 2, 3]: 3
17) Reduce min of [1, 2, 3]: 1
18) Square of 3: 9
19) Square root of 9: 3.0
20) Exponential of 2.0: 7.389056
21) Logarithm of 10.0: 2.3025851
22) Sine of 3.14: 0.001592548
23) Cosine of 3.14: -0.99999875
24) Tangent of 3.14: -0.0015925501
25) Absolute of -5: 5
26) Floor of 3.7: 3.0
27) Ceiling of 3.7: 4.0
28) Concatenated array:
 [[1]
 [2]
 [3]
 [4]]
29) Array of ones:
 [[1. 1.]
 [1. 1.]]
30) Array of zeros:
 [[0. 0.]
 [0. 0.]]
31) Reduce product of [1, 2, 3